# Generated by Django 4.2.29 on 2026-03-29 14:35

import apps.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categoryrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybudget',
            name='month',
            field=models.CharField(max_length=7, validators=[apps.categories.models.validate_month]),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'rule_bucket'], name='idx_cat_user_bucket'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='idx_cat_user_type'),
        ),
    ]
