# Generated by Django 4.2.29 on 2026-03-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_done',
            field=models.BooleanField(default=False),
        ),
    ]
