# Generated by Django 4.2.9 on 2026-03-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('icon', models.CharField(default='🏦', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'savings_accounts',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='SavingsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_target', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('needs_target', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('wants_target', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('savings_tolerance', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('needs_tolerance', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('wants_tolerance', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('savings_floor', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('needs_floor', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('wants_floor', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('compensation_order', models.JSONField(default=list)),
                ('window_months', models.IntegerField(default=3)),
                ('catchup_max_months', models.IntegerField(default=3)),
                ('mode', models.CharField(choices=[('strict', 'Règle fixe mensuelle'), ('adaptive', 'Règle adaptative glissante')], default='adaptive', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'savings_rules',
            },
        ),
    ]
