# Generated by Django 4.2.29 on 2026-03-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsrule',
            name='wants_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
