# Generated by Django 4.2.29 on 2026-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='idx_txn_user_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='idx_txn_user_type'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('import_hash__isnull', False)), fields=('user', 'import_hash'), name='uniq_user_import_hash'),
        ),
    ]
