# Generated by Django 4.2.9 on 2026-03-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('imported', 'Importé'), ('error', 'Erreur')], default='pending', max_length=10)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
