# Generated by Django 4.2.29 on 2026-03-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reconciliationentry',
            name='status',
            field=models.CharField(choices=[('auto', 'Correspondance automatique'), ('manual', 'Correspondance manuelle'), ('unmatched_app', 'Non trouvé en banque'), ('unmatched_bank', "Non trouvé dans l'app")], default='unmatched_bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
