# Generated by Django 4.2.9 on 2026-03-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savings', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense'), ('saving', 'Épargne')], max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('import', 'Import')], default='manual', max_length=10)),
                ('import_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='savings.savingsaccount')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
